name: Examples

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install spektral
      run: |
        python -m pip install --upgrade pip
        pip install .
    - name: Just one epoch
      run: |
        sed -i -e 's/epochs = /epochs = 1 #/g' examples/*.py
    - name: Graph Signal
      run: |
        cd examples/
        python graph_signal_classification_mnist.py
        cd ..
        
